!!python/object:trainer.training_utils.training_arguments
arch: mobilenetv2
dataloader: !!python/object:trainer.training_utils.dataloader_arguments
  batch_size: 256
  dataset: imagenet
  deterministic: true
  num_classes: 1000
  path: /data/imagenet
  pin_memory: true
  serialized: false
  val_split: 0.0
  workers: 16
device_gpu:
- 0
- 1
device_type: cuda
epochs: 120
log_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- ilena7440
- LSQFakeQuant
- out
- 88_20221028-110957
log_num_best_scores: 3
log_print_freq: 20
mode: lsq
n_gpu: 1
name: '88'
optimizer: !!python/object:trainer.training_utils.optimizer_arguments
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
output_dir: ./out
pre_trained: true
resume: false
resume_path: ''
scheduler: !!python/object:trainer.training_utils.scheduler_arguments
  gamma: 0.1
  milestones:
  - 30
  - 60
  - 90
  mode: multi_step
  update_per_batch: true
